spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wctdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:wct}
    password: ${DB_PASSWORD:wct}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
